pipeline {
   agent {
        docker {
            image 'docker.io/library/maven:3.6.1-jdk-8'
        }
    }

    stages {
        stage('Build app1') {
            steps {
                sh 'mvn -am -pl :app1 clean install'
            }
        }

    }
}
