pipeline {
//    agent {
//         docker {
//             image 'docker.io/library/maven:3.6.1-jdk-8'
//         }
//     }

    agent any

    stages {
        stage('Build app2') {
            steps {
                sh 'mvn -f apps/app2/pom.xml clean install'
            }
        }

    }
}
